// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_api.proto

#include "book_api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace lists {
namespace book {
namespace api {
PROTOBUF_CONSTEXPR ListBooksRequest::ListBooksRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.page_)*/0
  , /*decltype(_impl_.page_size_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ListBooksRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListBooksRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListBooksRequestDefaultTypeInternal() {}
  union {
    ListBooksRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListBooksRequestDefaultTypeInternal _ListBooksRequest_default_instance_;
PROTOBUF_CONSTEXPR ListBooksResponse::ListBooksResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.books_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ListBooksResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListBooksResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListBooksResponseDefaultTypeInternal() {}
  union {
    ListBooksResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListBooksResponseDefaultTypeInternal _ListBooksResponse_default_instance_;
PROTOBUF_CONSTEXPR GetBookRequest::GetBookRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetBookRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBookRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBookRequestDefaultTypeInternal() {}
  union {
    GetBookRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBookRequestDefaultTypeInternal _GetBookRequest_default_instance_;
PROTOBUF_CONSTEXPR GetBookResponse::GetBookResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.book_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetBookResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBookResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBookResponseDefaultTypeInternal() {}
  union {
    GetBookResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBookResponseDefaultTypeInternal _GetBookResponse_default_instance_;
PROTOBUF_CONSTEXPR CreateBookRequest::CreateBookRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.title_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cover_image_url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.author_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.note_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.start_date_)*/nullptr
  , /*decltype(_impl_.end_date_)*/nullptr
  , /*decltype(_impl_.rating_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateBookRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateBookRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateBookRequestDefaultTypeInternal() {}
  union {
    CreateBookRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateBookRequestDefaultTypeInternal _CreateBookRequest_default_instance_;
PROTOBUF_CONSTEXPR CreateBookResponse::CreateBookResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.book_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateBookResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateBookResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateBookResponseDefaultTypeInternal() {}
  union {
    CreateBookResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateBookResponseDefaultTypeInternal _CreateBookResponse_default_instance_;
PROTOBUF_CONSTEXPR UpdateBookRequest::UpdateBookRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.title_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cover_image_url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.author_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.note_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.start_date_)*/nullptr
  , /*decltype(_impl_.end_date_)*/nullptr
  , /*decltype(_impl_.id_)*/int64_t{0}
  , /*decltype(_impl_.rating_)*/0} {}
struct UpdateBookRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateBookRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateBookRequestDefaultTypeInternal() {}
  union {
    UpdateBookRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateBookRequestDefaultTypeInternal _UpdateBookRequest_default_instance_;
PROTOBUF_CONSTEXPR UpdateBookResponse::UpdateBookResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.book_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateBookResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateBookResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateBookResponseDefaultTypeInternal() {}
  union {
    UpdateBookResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateBookResponseDefaultTypeInternal _UpdateBookResponse_default_instance_;
}  // namespace api
}  // namespace book
}  // namespace lists
static ::_pb::Metadata file_level_metadata_book_5fapi_2eproto[8];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_book_5fapi_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_book_5fapi_2eproto = nullptr;

const uint32_t TableStruct_book_5fapi_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::ListBooksRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::ListBooksRequest, _impl_.page_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::ListBooksRequest, _impl_.page_size_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::ListBooksResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::ListBooksResponse, _impl_.books_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::GetBookRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::GetBookRequest, _impl_.id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::GetBookResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::GetBookResponse, _impl_.book_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _impl_.title_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _impl_.cover_image_url_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _impl_.author_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _impl_.start_date_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _impl_.end_date_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _impl_.rating_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookRequest, _impl_.note_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::CreateBookResponse, _impl_.book_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.title_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.cover_image_url_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.author_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.start_date_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.end_date_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.rating_),
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookRequest, _impl_.note_),
  ~0u,
  0,
  1,
  2,
  4,
  5,
  6,
  3,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lists::book::api::UpdateBookResponse, _impl_.book_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::lists::book::api::ListBooksRequest)},
  { 8, -1, -1, sizeof(::lists::book::api::ListBooksResponse)},
  { 15, -1, -1, sizeof(::lists::book::api::GetBookRequest)},
  { 22, -1, -1, sizeof(::lists::book::api::GetBookResponse)},
  { 29, -1, -1, sizeof(::lists::book::api::CreateBookRequest)},
  { 42, -1, -1, sizeof(::lists::book::api::CreateBookResponse)},
  { 49, 63, -1, sizeof(::lists::book::api::UpdateBookRequest)},
  { 71, -1, -1, sizeof(::lists::book::api::UpdateBookResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::lists::book::api::_ListBooksRequest_default_instance_._instance,
  &::lists::book::api::_ListBooksResponse_default_instance_._instance,
  &::lists::book::api::_GetBookRequest_default_instance_._instance,
  &::lists::book::api::_GetBookResponse_default_instance_._instance,
  &::lists::book::api::_CreateBookRequest_default_instance_._instance,
  &::lists::book::api::_CreateBookResponse_default_instance_._instance,
  &::lists::book::api::_UpdateBookRequest_default_instance_._instance,
  &::lists::book::api::_UpdateBookResponse_default_instance_._instance,
};

const char descriptor_table_protodef_book_5fapi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016book_api.proto\022\016lists.book.api\032\037google"
  "/protobuf/timestamp.proto\032\nbook.proto\"3\n"
  "\020ListBooksRequest\022\014\n\004page\030\001 \001(\005\022\021\n\tpage_"
  "size\030\002 \001(\005\"8\n\021ListBooksResponse\022#\n\005books"
  "\030\001 \003(\0132\024.lists.book.BookCard\"\034\n\016GetBookR"
  "equest\022\n\n\002id\030\001 \001(\003\"1\n\017GetBookResponse\022\036\n"
  "\004book\030\001 \001(\0132\020.lists.book.Book\"\333\001\n\021Create"
  "BookRequest\022\r\n\005title\030\001 \001(\t\022\027\n\017cover_imag"
  "e_url\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\022.\n\nstart_dat"
  "e\030\004 \001(\0132\032.google.protobuf.Timestamp\022,\n\010e"
  "nd_date\030\005 \001(\0132\032.google.protobuf.Timestam"
  "p\022\"\n\006rating\030\006 \001(\0162\022.lists.book.Rating\022\014\n"
  "\004note\030\007 \001(\t\"4\n\022CreateBookResponse\022\036\n\004boo"
  "k\030\001 \001(\0132\020.lists.book.Book\"\343\002\n\021UpdateBook"
  "Request\022\n\n\002id\030\001 \001(\003\022\022\n\005title\030\002 \001(\tH\000\210\001\001\022"
  "\034\n\017cover_image_url\030\003 \001(\tH\001\210\001\001\022\023\n\006author\030"
  "\004 \001(\tH\002\210\001\001\0223\n\nstart_date\030\005 \001(\0132\032.google."
  "protobuf.TimestampH\003\210\001\001\0221\n\010end_date\030\006 \001("
  "\0132\032.google.protobuf.TimestampH\004\210\001\001\022\'\n\006ra"
  "ting\030\007 \001(\0162\022.lists.book.RatingH\005\210\001\001\022\021\n\004n"
  "ote\030\010 \001(\tH\006\210\001\001B\010\n\006_titleB\022\n\020_cover_image"
  "_urlB\t\n\007_authorB\r\n\013_start_dateB\013\n\t_end_d"
  "ateB\t\n\007_ratingB\007\n\005_note\"4\n\022UpdateBookRes"
  "ponse\022\036\n\004book\030\001 \001(\0132\020.lists.book.BookB\003\370"
  "\001\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_book_5fapi_2eproto_deps[2] = {
  &::descriptor_table_book_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_book_5fapi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_book_5fapi_2eproto = {
    false, false, 970, descriptor_table_protodef_book_5fapi_2eproto,
    "book_api.proto",
    &descriptor_table_book_5fapi_2eproto_once, descriptor_table_book_5fapi_2eproto_deps, 2, 8,
    schemas, file_default_instances, TableStruct_book_5fapi_2eproto::offsets,
    file_level_metadata_book_5fapi_2eproto, file_level_enum_descriptors_book_5fapi_2eproto,
    file_level_service_descriptors_book_5fapi_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_book_5fapi_2eproto_getter() {
  return &descriptor_table_book_5fapi_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_book_5fapi_2eproto(&descriptor_table_book_5fapi_2eproto);
namespace lists {
namespace book {
namespace api {

// ===================================================================

class ListBooksRequest::_Internal {
 public:
};

ListBooksRequest::ListBooksRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.ListBooksRequest)
}
ListBooksRequest::ListBooksRequest(const ListBooksRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ListBooksRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.page_){}
    , decltype(_impl_.page_size_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.page_, &from._impl_.page_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.page_size_) -
    reinterpret_cast<char*>(&_impl_.page_)) + sizeof(_impl_.page_size_));
  // @@protoc_insertion_point(copy_constructor:lists.book.api.ListBooksRequest)
}

inline void ListBooksRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.page_){0}
    , decltype(_impl_.page_size_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ListBooksRequest::~ListBooksRequest() {
  // @@protoc_insertion_point(destructor:lists.book.api.ListBooksRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ListBooksRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ListBooksRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ListBooksRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.ListBooksRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.page_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.page_size_) -
      reinterpret_cast<char*>(&_impl_.page_)) + sizeof(_impl_.page_size_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ListBooksRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 page = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.page_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 page_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.page_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ListBooksRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.ListBooksRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 page = 1;
  if (this->_internal_page() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_page(), target);
  }

  // int32 page_size = 2;
  if (this->_internal_page_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_page_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.ListBooksRequest)
  return target;
}

size_t ListBooksRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.ListBooksRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 page = 1;
  if (this->_internal_page() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_page());
  }

  // int32 page_size = 2;
  if (this->_internal_page_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_page_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ListBooksRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ListBooksRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ListBooksRequest::GetClassData() const { return &_class_data_; }


void ListBooksRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ListBooksRequest*>(&to_msg);
  auto& from = static_cast<const ListBooksRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.ListBooksRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_page() != 0) {
    _this->_internal_set_page(from._internal_page());
  }
  if (from._internal_page_size() != 0) {
    _this->_internal_set_page_size(from._internal_page_size());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ListBooksRequest::CopyFrom(const ListBooksRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.ListBooksRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListBooksRequest::IsInitialized() const {
  return true;
}

void ListBooksRequest::InternalSwap(ListBooksRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ListBooksRequest, _impl_.page_size_)
      + sizeof(ListBooksRequest::_impl_.page_size_)
      - PROTOBUF_FIELD_OFFSET(ListBooksRequest, _impl_.page_)>(
          reinterpret_cast<char*>(&_impl_.page_),
          reinterpret_cast<char*>(&other->_impl_.page_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ListBooksRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[0]);
}

// ===================================================================

class ListBooksResponse::_Internal {
 public:
};

void ListBooksResponse::clear_books() {
  _impl_.books_.Clear();
}
ListBooksResponse::ListBooksResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.ListBooksResponse)
}
ListBooksResponse::ListBooksResponse(const ListBooksResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ListBooksResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.books_){from._impl_.books_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:lists.book.api.ListBooksResponse)
}

inline void ListBooksResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.books_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ListBooksResponse::~ListBooksResponse() {
  // @@protoc_insertion_point(destructor:lists.book.api.ListBooksResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ListBooksResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.books_.~RepeatedPtrField();
}

void ListBooksResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ListBooksResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.ListBooksResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.books_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ListBooksResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .lists.book.BookCard books = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_books(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ListBooksResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.ListBooksResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .lists.book.BookCard books = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_books_size()); i < n; i++) {
    const auto& repfield = this->_internal_books(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.ListBooksResponse)
  return target;
}

size_t ListBooksResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.ListBooksResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .lists.book.BookCard books = 1;
  total_size += 1UL * this->_internal_books_size();
  for (const auto& msg : this->_impl_.books_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ListBooksResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ListBooksResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ListBooksResponse::GetClassData() const { return &_class_data_; }


void ListBooksResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ListBooksResponse*>(&to_msg);
  auto& from = static_cast<const ListBooksResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.ListBooksResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.books_.MergeFrom(from._impl_.books_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ListBooksResponse::CopyFrom(const ListBooksResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.ListBooksResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListBooksResponse::IsInitialized() const {
  return true;
}

void ListBooksResponse::InternalSwap(ListBooksResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.books_.InternalSwap(&other->_impl_.books_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ListBooksResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[1]);
}

// ===================================================================

class GetBookRequest::_Internal {
 public:
};

GetBookRequest::GetBookRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.GetBookRequest)
}
GetBookRequest::GetBookRequest(const GetBookRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetBookRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:lists.book.api.GetBookRequest)
}

inline void GetBookRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetBookRequest::~GetBookRequest() {
  // @@protoc_insertion_point(destructor:lists.book.api.GetBookRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetBookRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetBookRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetBookRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.GetBookRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetBookRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetBookRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.GetBookRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.GetBookRequest)
  return target;
}

size_t GetBookRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.GetBookRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetBookRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetBookRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetBookRequest::GetClassData() const { return &_class_data_; }


void GetBookRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetBookRequest*>(&to_msg);
  auto& from = static_cast<const GetBookRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.GetBookRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetBookRequest::CopyFrom(const GetBookRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.GetBookRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetBookRequest::IsInitialized() const {
  return true;
}

void GetBookRequest::InternalSwap(GetBookRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetBookRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[2]);
}

// ===================================================================

class GetBookResponse::_Internal {
 public:
  static const ::lists::book::Book& book(const GetBookResponse* msg);
};

const ::lists::book::Book&
GetBookResponse::_Internal::book(const GetBookResponse* msg) {
  return *msg->_impl_.book_;
}
void GetBookResponse::clear_book() {
  if (GetArenaForAllocation() == nullptr && _impl_.book_ != nullptr) {
    delete _impl_.book_;
  }
  _impl_.book_ = nullptr;
}
GetBookResponse::GetBookResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.GetBookResponse)
}
GetBookResponse::GetBookResponse(const GetBookResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetBookResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.book_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_book()) {
    _this->_impl_.book_ = new ::lists::book::Book(*from._impl_.book_);
  }
  // @@protoc_insertion_point(copy_constructor:lists.book.api.GetBookResponse)
}

inline void GetBookResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.book_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetBookResponse::~GetBookResponse() {
  // @@protoc_insertion_point(destructor:lists.book.api.GetBookResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetBookResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.book_;
}

void GetBookResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetBookResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.GetBookResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.book_ != nullptr) {
    delete _impl_.book_;
  }
  _impl_.book_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetBookResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .lists.book.Book book = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_book(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetBookResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.GetBookResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .lists.book.Book book = 1;
  if (this->_internal_has_book()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::book(this),
        _Internal::book(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.GetBookResponse)
  return target;
}

size_t GetBookResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.GetBookResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .lists.book.Book book = 1;
  if (this->_internal_has_book()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.book_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetBookResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetBookResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetBookResponse::GetClassData() const { return &_class_data_; }


void GetBookResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetBookResponse*>(&to_msg);
  auto& from = static_cast<const GetBookResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.GetBookResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_book()) {
    _this->_internal_mutable_book()->::lists::book::Book::MergeFrom(
        from._internal_book());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetBookResponse::CopyFrom(const GetBookResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.GetBookResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetBookResponse::IsInitialized() const {
  return true;
}

void GetBookResponse::InternalSwap(GetBookResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.book_, other->_impl_.book_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetBookResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[3]);
}

// ===================================================================

class CreateBookRequest::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& start_date(const CreateBookRequest* msg);
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& end_date(const CreateBookRequest* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
CreateBookRequest::_Internal::start_date(const CreateBookRequest* msg) {
  return *msg->_impl_.start_date_;
}
const ::PROTOBUF_NAMESPACE_ID::Timestamp&
CreateBookRequest::_Internal::end_date(const CreateBookRequest* msg) {
  return *msg->_impl_.end_date_;
}
void CreateBookRequest::clear_start_date() {
  if (GetArenaForAllocation() == nullptr && _impl_.start_date_ != nullptr) {
    delete _impl_.start_date_;
  }
  _impl_.start_date_ = nullptr;
}
void CreateBookRequest::clear_end_date() {
  if (GetArenaForAllocation() == nullptr && _impl_.end_date_ != nullptr) {
    delete _impl_.end_date_;
  }
  _impl_.end_date_ = nullptr;
}
CreateBookRequest::CreateBookRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.CreateBookRequest)
}
CreateBookRequest::CreateBookRequest(const CreateBookRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateBookRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.title_){}
    , decltype(_impl_.cover_image_url_){}
    , decltype(_impl_.author_){}
    , decltype(_impl_.note_){}
    , decltype(_impl_.start_date_){nullptr}
    , decltype(_impl_.end_date_){nullptr}
    , decltype(_impl_.rating_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.title_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.title_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_title().empty()) {
    _this->_impl_.title_.Set(from._internal_title(), 
      _this->GetArenaForAllocation());
  }
  _impl_.cover_image_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cover_image_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_cover_image_url().empty()) {
    _this->_impl_.cover_image_url_.Set(from._internal_cover_image_url(), 
      _this->GetArenaForAllocation());
  }
  _impl_.author_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.author_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_author().empty()) {
    _this->_impl_.author_.Set(from._internal_author(), 
      _this->GetArenaForAllocation());
  }
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_note().empty()) {
    _this->_impl_.note_.Set(from._internal_note(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_start_date()) {
    _this->_impl_.start_date_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.start_date_);
  }
  if (from._internal_has_end_date()) {
    _this->_impl_.end_date_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.end_date_);
  }
  _this->_impl_.rating_ = from._impl_.rating_;
  // @@protoc_insertion_point(copy_constructor:lists.book.api.CreateBookRequest)
}

inline void CreateBookRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.title_){}
    , decltype(_impl_.cover_image_url_){}
    , decltype(_impl_.author_){}
    , decltype(_impl_.note_){}
    , decltype(_impl_.start_date_){nullptr}
    , decltype(_impl_.end_date_){nullptr}
    , decltype(_impl_.rating_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.title_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.title_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.cover_image_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cover_image_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.author_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.author_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CreateBookRequest::~CreateBookRequest() {
  // @@protoc_insertion_point(destructor:lists.book.api.CreateBookRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateBookRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.title_.Destroy();
  _impl_.cover_image_url_.Destroy();
  _impl_.author_.Destroy();
  _impl_.note_.Destroy();
  if (this != internal_default_instance()) delete _impl_.start_date_;
  if (this != internal_default_instance()) delete _impl_.end_date_;
}

void CreateBookRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateBookRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.CreateBookRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.title_.ClearToEmpty();
  _impl_.cover_image_url_.ClearToEmpty();
  _impl_.author_.ClearToEmpty();
  _impl_.note_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.start_date_ != nullptr) {
    delete _impl_.start_date_;
  }
  _impl_.start_date_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.end_date_ != nullptr) {
    delete _impl_.end_date_;
  }
  _impl_.end_date_ = nullptr;
  _impl_.rating_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateBookRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string title = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_title();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.CreateBookRequest.title"));
        } else
          goto handle_unusual;
        continue;
      // string cover_image_url = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_cover_image_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.CreateBookRequest.cover_image_url"));
        } else
          goto handle_unusual;
        continue;
      // string author = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_author();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.CreateBookRequest.author"));
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp start_date = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_start_date(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp end_date = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_end_date(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .lists.book.Rating rating = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_rating(static_cast<::lists::book::Rating>(val));
        } else
          goto handle_unusual;
        continue;
      // string note = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_note();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.CreateBookRequest.note"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateBookRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.CreateBookRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string title = 1;
  if (!this->_internal_title().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_title().data(), static_cast<int>(this->_internal_title().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.CreateBookRequest.title");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_title(), target);
  }

  // string cover_image_url = 2;
  if (!this->_internal_cover_image_url().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_cover_image_url().data(), static_cast<int>(this->_internal_cover_image_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.CreateBookRequest.cover_image_url");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_cover_image_url(), target);
  }

  // string author = 3;
  if (!this->_internal_author().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_author().data(), static_cast<int>(this->_internal_author().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.CreateBookRequest.author");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_author(), target);
  }

  // .google.protobuf.Timestamp start_date = 4;
  if (this->_internal_has_start_date()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::start_date(this),
        _Internal::start_date(this).GetCachedSize(), target, stream);
  }

  // .google.protobuf.Timestamp end_date = 5;
  if (this->_internal_has_end_date()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::end_date(this),
        _Internal::end_date(this).GetCachedSize(), target, stream);
  }

  // .lists.book.Rating rating = 6;
  if (this->_internal_rating() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      6, this->_internal_rating(), target);
  }

  // string note = 7;
  if (!this->_internal_note().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_note().data(), static_cast<int>(this->_internal_note().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.CreateBookRequest.note");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_note(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.CreateBookRequest)
  return target;
}

size_t CreateBookRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.CreateBookRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string title = 1;
  if (!this->_internal_title().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_title());
  }

  // string cover_image_url = 2;
  if (!this->_internal_cover_image_url().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_cover_image_url());
  }

  // string author = 3;
  if (!this->_internal_author().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_author());
  }

  // string note = 7;
  if (!this->_internal_note().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_note());
  }

  // .google.protobuf.Timestamp start_date = 4;
  if (this->_internal_has_start_date()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.start_date_);
  }

  // .google.protobuf.Timestamp end_date = 5;
  if (this->_internal_has_end_date()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.end_date_);
  }

  // .lists.book.Rating rating = 6;
  if (this->_internal_rating() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_rating());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateBookRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateBookRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateBookRequest::GetClassData() const { return &_class_data_; }


void CreateBookRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateBookRequest*>(&to_msg);
  auto& from = static_cast<const CreateBookRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.CreateBookRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_title().empty()) {
    _this->_internal_set_title(from._internal_title());
  }
  if (!from._internal_cover_image_url().empty()) {
    _this->_internal_set_cover_image_url(from._internal_cover_image_url());
  }
  if (!from._internal_author().empty()) {
    _this->_internal_set_author(from._internal_author());
  }
  if (!from._internal_note().empty()) {
    _this->_internal_set_note(from._internal_note());
  }
  if (from._internal_has_start_date()) {
    _this->_internal_mutable_start_date()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_start_date());
  }
  if (from._internal_has_end_date()) {
    _this->_internal_mutable_end_date()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_end_date());
  }
  if (from._internal_rating() != 0) {
    _this->_internal_set_rating(from._internal_rating());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateBookRequest::CopyFrom(const CreateBookRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.CreateBookRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateBookRequest::IsInitialized() const {
  return true;
}

void CreateBookRequest::InternalSwap(CreateBookRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.title_, lhs_arena,
      &other->_impl_.title_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.cover_image_url_, lhs_arena,
      &other->_impl_.cover_image_url_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.author_, lhs_arena,
      &other->_impl_.author_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.note_, lhs_arena,
      &other->_impl_.note_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateBookRequest, _impl_.rating_)
      + sizeof(CreateBookRequest::_impl_.rating_)
      - PROTOBUF_FIELD_OFFSET(CreateBookRequest, _impl_.start_date_)>(
          reinterpret_cast<char*>(&_impl_.start_date_),
          reinterpret_cast<char*>(&other->_impl_.start_date_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateBookRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[4]);
}

// ===================================================================

class CreateBookResponse::_Internal {
 public:
  static const ::lists::book::Book& book(const CreateBookResponse* msg);
};

const ::lists::book::Book&
CreateBookResponse::_Internal::book(const CreateBookResponse* msg) {
  return *msg->_impl_.book_;
}
void CreateBookResponse::clear_book() {
  if (GetArenaForAllocation() == nullptr && _impl_.book_ != nullptr) {
    delete _impl_.book_;
  }
  _impl_.book_ = nullptr;
}
CreateBookResponse::CreateBookResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.CreateBookResponse)
}
CreateBookResponse::CreateBookResponse(const CreateBookResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateBookResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.book_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_book()) {
    _this->_impl_.book_ = new ::lists::book::Book(*from._impl_.book_);
  }
  // @@protoc_insertion_point(copy_constructor:lists.book.api.CreateBookResponse)
}

inline void CreateBookResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.book_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CreateBookResponse::~CreateBookResponse() {
  // @@protoc_insertion_point(destructor:lists.book.api.CreateBookResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateBookResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.book_;
}

void CreateBookResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateBookResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.CreateBookResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.book_ != nullptr) {
    delete _impl_.book_;
  }
  _impl_.book_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateBookResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .lists.book.Book book = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_book(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateBookResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.CreateBookResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .lists.book.Book book = 1;
  if (this->_internal_has_book()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::book(this),
        _Internal::book(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.CreateBookResponse)
  return target;
}

size_t CreateBookResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.CreateBookResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .lists.book.Book book = 1;
  if (this->_internal_has_book()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.book_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateBookResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateBookResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateBookResponse::GetClassData() const { return &_class_data_; }


void CreateBookResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateBookResponse*>(&to_msg);
  auto& from = static_cast<const CreateBookResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.CreateBookResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_book()) {
    _this->_internal_mutable_book()->::lists::book::Book::MergeFrom(
        from._internal_book());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateBookResponse::CopyFrom(const CreateBookResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.CreateBookResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateBookResponse::IsInitialized() const {
  return true;
}

void CreateBookResponse::InternalSwap(CreateBookResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.book_, other->_impl_.book_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateBookResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[5]);
}

// ===================================================================

class UpdateBookRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<UpdateBookRequest>()._impl_._has_bits_);
  static void set_has_title(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_cover_image_url(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_author(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& start_date(const UpdateBookRequest* msg);
  static void set_has_start_date(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& end_date(const UpdateBookRequest* msg);
  static void set_has_end_date(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_rating(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_note(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
UpdateBookRequest::_Internal::start_date(const UpdateBookRequest* msg) {
  return *msg->_impl_.start_date_;
}
const ::PROTOBUF_NAMESPACE_ID::Timestamp&
UpdateBookRequest::_Internal::end_date(const UpdateBookRequest* msg) {
  return *msg->_impl_.end_date_;
}
void UpdateBookRequest::clear_start_date() {
  if (_impl_.start_date_ != nullptr) _impl_.start_date_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
void UpdateBookRequest::clear_end_date() {
  if (_impl_.end_date_ != nullptr) _impl_.end_date_->Clear();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
UpdateBookRequest::UpdateBookRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.UpdateBookRequest)
}
UpdateBookRequest::UpdateBookRequest(const UpdateBookRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateBookRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.title_){}
    , decltype(_impl_.cover_image_url_){}
    , decltype(_impl_.author_){}
    , decltype(_impl_.note_){}
    , decltype(_impl_.start_date_){nullptr}
    , decltype(_impl_.end_date_){nullptr}
    , decltype(_impl_.id_){}
    , decltype(_impl_.rating_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.title_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.title_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_title()) {
    _this->_impl_.title_.Set(from._internal_title(), 
      _this->GetArenaForAllocation());
  }
  _impl_.cover_image_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cover_image_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_cover_image_url()) {
    _this->_impl_.cover_image_url_.Set(from._internal_cover_image_url(), 
      _this->GetArenaForAllocation());
  }
  _impl_.author_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.author_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_author()) {
    _this->_impl_.author_.Set(from._internal_author(), 
      _this->GetArenaForAllocation());
  }
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_note()) {
    _this->_impl_.note_.Set(from._internal_note(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_start_date()) {
    _this->_impl_.start_date_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.start_date_);
  }
  if (from._internal_has_end_date()) {
    _this->_impl_.end_date_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.end_date_);
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.rating_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.rating_));
  // @@protoc_insertion_point(copy_constructor:lists.book.api.UpdateBookRequest)
}

inline void UpdateBookRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.title_){}
    , decltype(_impl_.cover_image_url_){}
    , decltype(_impl_.author_){}
    , decltype(_impl_.note_){}
    , decltype(_impl_.start_date_){nullptr}
    , decltype(_impl_.end_date_){nullptr}
    , decltype(_impl_.id_){int64_t{0}}
    , decltype(_impl_.rating_){0}
  };
  _impl_.title_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.title_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.cover_image_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cover_image_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.author_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.author_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UpdateBookRequest::~UpdateBookRequest() {
  // @@protoc_insertion_point(destructor:lists.book.api.UpdateBookRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateBookRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.title_.Destroy();
  _impl_.cover_image_url_.Destroy();
  _impl_.author_.Destroy();
  _impl_.note_.Destroy();
  if (this != internal_default_instance()) delete _impl_.start_date_;
  if (this != internal_default_instance()) delete _impl_.end_date_;
}

void UpdateBookRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateBookRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.UpdateBookRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.cover_image_url_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.author_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.note_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(_impl_.start_date_ != nullptr);
      _impl_.start_date_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(_impl_.end_date_ != nullptr);
      _impl_.end_date_->Clear();
    }
  }
  _impl_.id_ = int64_t{0};
  _impl_.rating_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateBookRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string title = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_title();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.UpdateBookRequest.title"));
        } else
          goto handle_unusual;
        continue;
      // optional string cover_image_url = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_cover_image_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.UpdateBookRequest.cover_image_url"));
        } else
          goto handle_unusual;
        continue;
      // optional string author = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_author();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.UpdateBookRequest.author"));
        } else
          goto handle_unusual;
        continue;
      // optional .google.protobuf.Timestamp start_date = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_start_date(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .google.protobuf.Timestamp end_date = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_end_date(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .lists.book.Rating rating = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_rating(static_cast<::lists::book::Rating>(val));
        } else
          goto handle_unusual;
        continue;
      // optional string note = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_note();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lists.book.api.UpdateBookRequest.note"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdateBookRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.UpdateBookRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_id(), target);
  }

  // optional string title = 2;
  if (_internal_has_title()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_title().data(), static_cast<int>(this->_internal_title().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.UpdateBookRequest.title");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_title(), target);
  }

  // optional string cover_image_url = 3;
  if (_internal_has_cover_image_url()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_cover_image_url().data(), static_cast<int>(this->_internal_cover_image_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.UpdateBookRequest.cover_image_url");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_cover_image_url(), target);
  }

  // optional string author = 4;
  if (_internal_has_author()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_author().data(), static_cast<int>(this->_internal_author().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.UpdateBookRequest.author");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_author(), target);
  }

  // optional .google.protobuf.Timestamp start_date = 5;
  if (_internal_has_start_date()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::start_date(this),
        _Internal::start_date(this).GetCachedSize(), target, stream);
  }

  // optional .google.protobuf.Timestamp end_date = 6;
  if (_internal_has_end_date()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::end_date(this),
        _Internal::end_date(this).GetCachedSize(), target, stream);
  }

  // optional .lists.book.Rating rating = 7;
  if (_internal_has_rating()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      7, this->_internal_rating(), target);
  }

  // optional string note = 8;
  if (_internal_has_note()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_note().data(), static_cast<int>(this->_internal_note().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lists.book.api.UpdateBookRequest.note");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_note(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.UpdateBookRequest)
  return target;
}

size_t UpdateBookRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.UpdateBookRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string title = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_title());
    }

    // optional string cover_image_url = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_cover_image_url());
    }

    // optional string author = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_author());
    }

    // optional string note = 8;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_note());
    }

    // optional .google.protobuf.Timestamp start_date = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.start_date_);
    }

    // optional .google.protobuf.Timestamp end_date = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.end_date_);
    }

  }
  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_id());
  }

  // optional .lists.book.Rating rating = 7;
  if (cached_has_bits & 0x00000040u) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_rating());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateBookRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateBookRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateBookRequest::GetClassData() const { return &_class_data_; }


void UpdateBookRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateBookRequest*>(&to_msg);
  auto& from = static_cast<const UpdateBookRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.UpdateBookRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_title(from._internal_title());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_cover_image_url(from._internal_cover_image_url());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_author(from._internal_author());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_note(from._internal_note());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_mutable_start_date()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
          from._internal_start_date());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_mutable_end_date()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
          from._internal_end_date());
    }
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (cached_has_bits & 0x00000040u) {
    _this->_internal_set_rating(from._internal_rating());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateBookRequest::CopyFrom(const UpdateBookRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.UpdateBookRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateBookRequest::IsInitialized() const {
  return true;
}

void UpdateBookRequest::InternalSwap(UpdateBookRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.title_, lhs_arena,
      &other->_impl_.title_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.cover_image_url_, lhs_arena,
      &other->_impl_.cover_image_url_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.author_, lhs_arena,
      &other->_impl_.author_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.note_, lhs_arena,
      &other->_impl_.note_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateBookRequest, _impl_.rating_)
      + sizeof(UpdateBookRequest::_impl_.rating_)
      - PROTOBUF_FIELD_OFFSET(UpdateBookRequest, _impl_.start_date_)>(
          reinterpret_cast<char*>(&_impl_.start_date_),
          reinterpret_cast<char*>(&other->_impl_.start_date_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateBookRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[6]);
}

// ===================================================================

class UpdateBookResponse::_Internal {
 public:
  static const ::lists::book::Book& book(const UpdateBookResponse* msg);
};

const ::lists::book::Book&
UpdateBookResponse::_Internal::book(const UpdateBookResponse* msg) {
  return *msg->_impl_.book_;
}
void UpdateBookResponse::clear_book() {
  if (GetArenaForAllocation() == nullptr && _impl_.book_ != nullptr) {
    delete _impl_.book_;
  }
  _impl_.book_ = nullptr;
}
UpdateBookResponse::UpdateBookResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lists.book.api.UpdateBookResponse)
}
UpdateBookResponse::UpdateBookResponse(const UpdateBookResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateBookResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.book_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_book()) {
    _this->_impl_.book_ = new ::lists::book::Book(*from._impl_.book_);
  }
  // @@protoc_insertion_point(copy_constructor:lists.book.api.UpdateBookResponse)
}

inline void UpdateBookResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.book_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UpdateBookResponse::~UpdateBookResponse() {
  // @@protoc_insertion_point(destructor:lists.book.api.UpdateBookResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateBookResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.book_;
}

void UpdateBookResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateBookResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:lists.book.api.UpdateBookResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.book_ != nullptr) {
    delete _impl_.book_;
  }
  _impl_.book_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateBookResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .lists.book.Book book = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_book(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdateBookResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lists.book.api.UpdateBookResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .lists.book.Book book = 1;
  if (this->_internal_has_book()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::book(this),
        _Internal::book(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lists.book.api.UpdateBookResponse)
  return target;
}

size_t UpdateBookResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lists.book.api.UpdateBookResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .lists.book.Book book = 1;
  if (this->_internal_has_book()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.book_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateBookResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateBookResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateBookResponse::GetClassData() const { return &_class_data_; }


void UpdateBookResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateBookResponse*>(&to_msg);
  auto& from = static_cast<const UpdateBookResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lists.book.api.UpdateBookResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_book()) {
    _this->_internal_mutable_book()->::lists::book::Book::MergeFrom(
        from._internal_book());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateBookResponse::CopyFrom(const UpdateBookResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lists.book.api.UpdateBookResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateBookResponse::IsInitialized() const {
  return true;
}

void UpdateBookResponse::InternalSwap(UpdateBookResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.book_, other->_impl_.book_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateBookResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_book_5fapi_2eproto_getter, &descriptor_table_book_5fapi_2eproto_once,
      file_level_metadata_book_5fapi_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace book
}  // namespace lists
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::lists::book::api::ListBooksRequest*
Arena::CreateMaybeMessage< ::lists::book::api::ListBooksRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::ListBooksRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::lists::book::api::ListBooksResponse*
Arena::CreateMaybeMessage< ::lists::book::api::ListBooksResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::ListBooksResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::lists::book::api::GetBookRequest*
Arena::CreateMaybeMessage< ::lists::book::api::GetBookRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::GetBookRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::lists::book::api::GetBookResponse*
Arena::CreateMaybeMessage< ::lists::book::api::GetBookResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::GetBookResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::lists::book::api::CreateBookRequest*
Arena::CreateMaybeMessage< ::lists::book::api::CreateBookRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::CreateBookRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::lists::book::api::CreateBookResponse*
Arena::CreateMaybeMessage< ::lists::book::api::CreateBookResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::CreateBookResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::lists::book::api::UpdateBookRequest*
Arena::CreateMaybeMessage< ::lists::book::api::UpdateBookRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::UpdateBookRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::lists::book::api::UpdateBookResponse*
Arena::CreateMaybeMessage< ::lists::book::api::UpdateBookResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lists::book::api::UpdateBookResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
