// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_book_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_book_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_book_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_book_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_book_2eproto;
namespace lists {
namespace book {
class Book;
struct BookDefaultTypeInternal;
extern BookDefaultTypeInternal _Book_default_instance_;
class BookCard;
struct BookCardDefaultTypeInternal;
extern BookCardDefaultTypeInternal _BookCard_default_instance_;
}  // namespace book
}  // namespace lists
PROTOBUF_NAMESPACE_OPEN
template<> ::lists::book::Book* Arena::CreateMaybeMessage<::lists::book::Book>(Arena*);
template<> ::lists::book::BookCard* Arena::CreateMaybeMessage<::lists::book::BookCard>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lists {
namespace book {

enum ReadingStatus : int {
  READING_STATUS_UNSPECIFIED = 0,
  READING_STATUS_NOT_STARTED = 1,
  READING_STATUS_READING = 2,
  READING_STATUS_FINISHED = 3,
  ReadingStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ReadingStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ReadingStatus_IsValid(int value);
constexpr ReadingStatus ReadingStatus_MIN = READING_STATUS_UNSPECIFIED;
constexpr ReadingStatus ReadingStatus_MAX = READING_STATUS_FINISHED;
constexpr int ReadingStatus_ARRAYSIZE = ReadingStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReadingStatus_descriptor();
template<typename T>
inline const std::string& ReadingStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ReadingStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ReadingStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ReadingStatus_descriptor(), enum_t_value);
}
inline bool ReadingStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ReadingStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ReadingStatus>(
    ReadingStatus_descriptor(), name, value);
}
enum Rating : int {
  RATING_UNSPECIFIED = 0,
  RATING_1 = 1,
  RATING_2 = 2,
  RATING_3 = 3,
  RATING_4 = 4,
  RATING_5 = 5,
  Rating_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Rating_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Rating_IsValid(int value);
constexpr Rating Rating_MIN = RATING_UNSPECIFIED;
constexpr Rating Rating_MAX = RATING_5;
constexpr int Rating_ARRAYSIZE = Rating_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Rating_descriptor();
template<typename T>
inline const std::string& Rating_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Rating>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Rating_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Rating_descriptor(), enum_t_value);
}
inline bool Rating_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Rating* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Rating>(
    Rating_descriptor(), name, value);
}
// ===================================================================

class Book final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lists.book.Book) */ {
 public:
  inline Book() : Book(nullptr) {}
  ~Book() override;
  explicit PROTOBUF_CONSTEXPR Book(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Book(const Book& from);
  Book(Book&& from) noexcept
    : Book() {
    *this = ::std::move(from);
  }

  inline Book& operator=(const Book& from) {
    CopyFrom(from);
    return *this;
  }
  inline Book& operator=(Book&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Book& default_instance() {
    return *internal_default_instance();
  }
  static inline const Book* internal_default_instance() {
    return reinterpret_cast<const Book*>(
               &_Book_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Book& a, Book& b) {
    a.Swap(&b);
  }
  inline void Swap(Book* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Book* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Book* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Book>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Book& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Book& from) {
    Book::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Book* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lists.book.Book";
  }
  protected:
  explicit Book(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTitleFieldNumber = 2,
    kCoverImageUrlFieldNumber = 3,
    kAuthorFieldNumber = 4,
    kNoteFieldNumber = 9,
    kStartDateFieldNumber = 5,
    kEndDateFieldNumber = 6,
    kCreatedAtFieldNumber = 20,
    kUpdatedAtFieldNumber = 21,
    kIdFieldNumber = 1,
    kRatingFieldNumber = 7,
    kStatusFieldNumber = 8,
  };
  // string title = 2;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string cover_image_url = 3;
  void clear_cover_image_url();
  const std::string& cover_image_url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cover_image_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cover_image_url();
  PROTOBUF_NODISCARD std::string* release_cover_image_url();
  void set_allocated_cover_image_url(std::string* cover_image_url);
  private:
  const std::string& _internal_cover_image_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cover_image_url(const std::string& value);
  std::string* _internal_mutable_cover_image_url();
  public:

  // string author = 4;
  void clear_author();
  const std::string& author() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_author(ArgT0&& arg0, ArgT... args);
  std::string* mutable_author();
  PROTOBUF_NODISCARD std::string* release_author();
  void set_allocated_author(std::string* author);
  private:
  const std::string& _internal_author() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_author(const std::string& value);
  std::string* _internal_mutable_author();
  public:

  // string note = 9;
  void clear_note();
  const std::string& note() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_note(ArgT0&& arg0, ArgT... args);
  std::string* mutable_note();
  PROTOBUF_NODISCARD std::string* release_note();
  void set_allocated_note(std::string* note);
  private:
  const std::string& _internal_note() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_note(const std::string& value);
  std::string* _internal_mutable_note();
  public:

  // .google.protobuf.Timestamp startDate = 5;
  bool has_startdate() const;
  private:
  bool _internal_has_startdate() const;
  public:
  void clear_startdate();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& startdate() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_startdate();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_startdate();
  void set_allocated_startdate(::PROTOBUF_NAMESPACE_ID::Timestamp* startdate);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_startdate() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_startdate();
  public:
  void unsafe_arena_set_allocated_startdate(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* startdate);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_startdate();

  // .google.protobuf.Timestamp endDate = 6;
  bool has_enddate() const;
  private:
  bool _internal_has_enddate() const;
  public:
  void clear_enddate();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& enddate() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_enddate();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_enddate();
  void set_allocated_enddate(::PROTOBUF_NAMESPACE_ID::Timestamp* enddate);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_enddate() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_enddate();
  public:
  void unsafe_arena_set_allocated_enddate(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* enddate);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_enddate();

  // .google.protobuf.Timestamp created_at = 20;
  bool has_created_at() const;
  private:
  bool _internal_has_created_at() const;
  public:
  void clear_created_at();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& created_at() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_created_at();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_created_at();
  void set_allocated_created_at(::PROTOBUF_NAMESPACE_ID::Timestamp* created_at);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_created_at() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_created_at();
  public:
  void unsafe_arena_set_allocated_created_at(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_created_at();

  // .google.protobuf.Timestamp updated_at = 21;
  bool has_updated_at() const;
  private:
  bool _internal_has_updated_at() const;
  public:
  void clear_updated_at();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& updated_at() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_updated_at();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_updated_at();
  void set_allocated_updated_at(::PROTOBUF_NAMESPACE_ID::Timestamp* updated_at);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_updated_at() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_updated_at();
  public:
  void unsafe_arena_set_allocated_updated_at(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* updated_at);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_updated_at();

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // .lists.book.Rating rating = 7;
  void clear_rating();
  ::lists::book::Rating rating() const;
  void set_rating(::lists::book::Rating value);
  private:
  ::lists::book::Rating _internal_rating() const;
  void _internal_set_rating(::lists::book::Rating value);
  public:

  // .lists.book.ReadingStatus status = 8;
  void clear_status();
  ::lists::book::ReadingStatus status() const;
  void set_status(::lists::book::ReadingStatus value);
  private:
  ::lists::book::ReadingStatus _internal_status() const;
  void _internal_set_status(::lists::book::ReadingStatus value);
  public:

  // @@protoc_insertion_point(class_scope:lists.book.Book)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cover_image_url_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr author_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr note_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* startdate_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* enddate_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* updated_at_;
    int64_t id_;
    int rating_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_book_2eproto;
};
// -------------------------------------------------------------------

class BookCard final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lists.book.BookCard) */ {
 public:
  inline BookCard() : BookCard(nullptr) {}
  ~BookCard() override;
  explicit PROTOBUF_CONSTEXPR BookCard(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BookCard(const BookCard& from);
  BookCard(BookCard&& from) noexcept
    : BookCard() {
    *this = ::std::move(from);
  }

  inline BookCard& operator=(const BookCard& from) {
    CopyFrom(from);
    return *this;
  }
  inline BookCard& operator=(BookCard&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BookCard& default_instance() {
    return *internal_default_instance();
  }
  static inline const BookCard* internal_default_instance() {
    return reinterpret_cast<const BookCard*>(
               &_BookCard_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BookCard& a, BookCard& b) {
    a.Swap(&b);
  }
  inline void Swap(BookCard* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BookCard* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BookCard* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BookCard>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BookCard& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BookCard& from) {
    BookCard::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BookCard* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lists.book.BookCard";
  }
  protected:
  explicit BookCard(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTitleFieldNumber = 2,
    kCoverImageUrlFieldNumber = 3,
    kIdFieldNumber = 1,
    kStatusFieldNumber = 4,
  };
  // string title = 2;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string cover_image_url = 3;
  void clear_cover_image_url();
  const std::string& cover_image_url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cover_image_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cover_image_url();
  PROTOBUF_NODISCARD std::string* release_cover_image_url();
  void set_allocated_cover_image_url(std::string* cover_image_url);
  private:
  const std::string& _internal_cover_image_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cover_image_url(const std::string& value);
  std::string* _internal_mutable_cover_image_url();
  public:

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // .lists.book.ReadingStatus status = 4;
  void clear_status();
  ::lists::book::ReadingStatus status() const;
  void set_status(::lists::book::ReadingStatus value);
  private:
  ::lists::book::ReadingStatus _internal_status() const;
  void _internal_set_status(::lists::book::ReadingStatus value);
  public:

  // @@protoc_insertion_point(class_scope:lists.book.BookCard)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cover_image_url_;
    int64_t id_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_book_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Book

// int64 id = 1;
inline void Book::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t Book::_internal_id() const {
  return _impl_.id_;
}
inline int64_t Book::id() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.id)
  return _internal_id();
}
inline void Book::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void Book::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:lists.book.Book.id)
}

// string title = 2;
inline void Book::clear_title() {
  _impl_.title_.ClearToEmpty();
}
inline const std::string& Book::title() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Book::set_title(ArgT0&& arg0, ArgT... args) {
 
 _impl_.title_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lists.book.Book.title)
}
inline std::string* Book::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.title)
  return _s;
}
inline const std::string& Book::_internal_title() const {
  return _impl_.title_.Get();
}
inline void Book::_internal_set_title(const std::string& value) {
  
  _impl_.title_.Set(value, GetArenaForAllocation());
}
inline std::string* Book::_internal_mutable_title() {
  
  return _impl_.title_.Mutable(GetArenaForAllocation());
}
inline std::string* Book::release_title() {
  // @@protoc_insertion_point(field_release:lists.book.Book.title)
  return _impl_.title_.Release();
}
inline void Book::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  _impl_.title_.SetAllocated(title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.title)
}

// string cover_image_url = 3;
inline void Book::clear_cover_image_url() {
  _impl_.cover_image_url_.ClearToEmpty();
}
inline const std::string& Book::cover_image_url() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.cover_image_url)
  return _internal_cover_image_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Book::set_cover_image_url(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cover_image_url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lists.book.Book.cover_image_url)
}
inline std::string* Book::mutable_cover_image_url() {
  std::string* _s = _internal_mutable_cover_image_url();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.cover_image_url)
  return _s;
}
inline const std::string& Book::_internal_cover_image_url() const {
  return _impl_.cover_image_url_.Get();
}
inline void Book::_internal_set_cover_image_url(const std::string& value) {
  
  _impl_.cover_image_url_.Set(value, GetArenaForAllocation());
}
inline std::string* Book::_internal_mutable_cover_image_url() {
  
  return _impl_.cover_image_url_.Mutable(GetArenaForAllocation());
}
inline std::string* Book::release_cover_image_url() {
  // @@protoc_insertion_point(field_release:lists.book.Book.cover_image_url)
  return _impl_.cover_image_url_.Release();
}
inline void Book::set_allocated_cover_image_url(std::string* cover_image_url) {
  if (cover_image_url != nullptr) {
    
  } else {
    
  }
  _impl_.cover_image_url_.SetAllocated(cover_image_url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cover_image_url_.IsDefault()) {
    _impl_.cover_image_url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.cover_image_url)
}

// string author = 4;
inline void Book::clear_author() {
  _impl_.author_.ClearToEmpty();
}
inline const std::string& Book::author() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.author)
  return _internal_author();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Book::set_author(ArgT0&& arg0, ArgT... args) {
 
 _impl_.author_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lists.book.Book.author)
}
inline std::string* Book::mutable_author() {
  std::string* _s = _internal_mutable_author();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.author)
  return _s;
}
inline const std::string& Book::_internal_author() const {
  return _impl_.author_.Get();
}
inline void Book::_internal_set_author(const std::string& value) {
  
  _impl_.author_.Set(value, GetArenaForAllocation());
}
inline std::string* Book::_internal_mutable_author() {
  
  return _impl_.author_.Mutable(GetArenaForAllocation());
}
inline std::string* Book::release_author() {
  // @@protoc_insertion_point(field_release:lists.book.Book.author)
  return _impl_.author_.Release();
}
inline void Book::set_allocated_author(std::string* author) {
  if (author != nullptr) {
    
  } else {
    
  }
  _impl_.author_.SetAllocated(author, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.author_.IsDefault()) {
    _impl_.author_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.author)
}

// .google.protobuf.Timestamp startDate = 5;
inline bool Book::_internal_has_startdate() const {
  return this != internal_default_instance() && _impl_.startdate_ != nullptr;
}
inline bool Book::has_startdate() const {
  return _internal_has_startdate();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::_internal_startdate() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.startdate_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::startdate() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.startDate)
  return _internal_startdate();
}
inline void Book::unsafe_arena_set_allocated_startdate(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* startdate) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.startdate_);
  }
  _impl_.startdate_ = startdate;
  if (startdate) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lists.book.Book.startDate)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::release_startdate() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.startdate_;
  _impl_.startdate_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::unsafe_arena_release_startdate() {
  // @@protoc_insertion_point(field_release:lists.book.Book.startDate)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.startdate_;
  _impl_.startdate_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::_internal_mutable_startdate() {
  
  if (_impl_.startdate_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.startdate_ = p;
  }
  return _impl_.startdate_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::mutable_startdate() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_startdate();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.startDate)
  return _msg;
}
inline void Book::set_allocated_startdate(::PROTOBUF_NAMESPACE_ID::Timestamp* startdate) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.startdate_);
  }
  if (startdate) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(startdate));
    if (message_arena != submessage_arena) {
      startdate = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, startdate, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.startdate_ = startdate;
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.startDate)
}

// .google.protobuf.Timestamp endDate = 6;
inline bool Book::_internal_has_enddate() const {
  return this != internal_default_instance() && _impl_.enddate_ != nullptr;
}
inline bool Book::has_enddate() const {
  return _internal_has_enddate();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::_internal_enddate() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.enddate_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::enddate() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.endDate)
  return _internal_enddate();
}
inline void Book::unsafe_arena_set_allocated_enddate(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* enddate) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.enddate_);
  }
  _impl_.enddate_ = enddate;
  if (enddate) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lists.book.Book.endDate)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::release_enddate() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.enddate_;
  _impl_.enddate_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::unsafe_arena_release_enddate() {
  // @@protoc_insertion_point(field_release:lists.book.Book.endDate)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.enddate_;
  _impl_.enddate_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::_internal_mutable_enddate() {
  
  if (_impl_.enddate_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.enddate_ = p;
  }
  return _impl_.enddate_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::mutable_enddate() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_enddate();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.endDate)
  return _msg;
}
inline void Book::set_allocated_enddate(::PROTOBUF_NAMESPACE_ID::Timestamp* enddate) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.enddate_);
  }
  if (enddate) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(enddate));
    if (message_arena != submessage_arena) {
      enddate = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, enddate, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.enddate_ = enddate;
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.endDate)
}

// .lists.book.Rating rating = 7;
inline void Book::clear_rating() {
  _impl_.rating_ = 0;
}
inline ::lists::book::Rating Book::_internal_rating() const {
  return static_cast< ::lists::book::Rating >(_impl_.rating_);
}
inline ::lists::book::Rating Book::rating() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.rating)
  return _internal_rating();
}
inline void Book::_internal_set_rating(::lists::book::Rating value) {
  
  _impl_.rating_ = value;
}
inline void Book::set_rating(::lists::book::Rating value) {
  _internal_set_rating(value);
  // @@protoc_insertion_point(field_set:lists.book.Book.rating)
}

// .lists.book.ReadingStatus status = 8;
inline void Book::clear_status() {
  _impl_.status_ = 0;
}
inline ::lists::book::ReadingStatus Book::_internal_status() const {
  return static_cast< ::lists::book::ReadingStatus >(_impl_.status_);
}
inline ::lists::book::ReadingStatus Book::status() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.status)
  return _internal_status();
}
inline void Book::_internal_set_status(::lists::book::ReadingStatus value) {
  
  _impl_.status_ = value;
}
inline void Book::set_status(::lists::book::ReadingStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:lists.book.Book.status)
}

// string note = 9;
inline void Book::clear_note() {
  _impl_.note_.ClearToEmpty();
}
inline const std::string& Book::note() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.note)
  return _internal_note();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Book::set_note(ArgT0&& arg0, ArgT... args) {
 
 _impl_.note_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lists.book.Book.note)
}
inline std::string* Book::mutable_note() {
  std::string* _s = _internal_mutable_note();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.note)
  return _s;
}
inline const std::string& Book::_internal_note() const {
  return _impl_.note_.Get();
}
inline void Book::_internal_set_note(const std::string& value) {
  
  _impl_.note_.Set(value, GetArenaForAllocation());
}
inline std::string* Book::_internal_mutable_note() {
  
  return _impl_.note_.Mutable(GetArenaForAllocation());
}
inline std::string* Book::release_note() {
  // @@protoc_insertion_point(field_release:lists.book.Book.note)
  return _impl_.note_.Release();
}
inline void Book::set_allocated_note(std::string* note) {
  if (note != nullptr) {
    
  } else {
    
  }
  _impl_.note_.SetAllocated(note, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.note_.IsDefault()) {
    _impl_.note_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.note)
}

// .google.protobuf.Timestamp created_at = 20;
inline bool Book::_internal_has_created_at() const {
  return this != internal_default_instance() && _impl_.created_at_ != nullptr;
}
inline bool Book::has_created_at() const {
  return _internal_has_created_at();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::_internal_created_at() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.created_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::created_at() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.created_at)
  return _internal_created_at();
}
inline void Book::unsafe_arena_set_allocated_created_at(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_at_);
  }
  _impl_.created_at_ = created_at;
  if (created_at) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lists.book.Book.created_at)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::release_created_at() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::unsafe_arena_release_created_at() {
  // @@protoc_insertion_point(field_release:lists.book.Book.created_at)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::_internal_mutable_created_at() {
  
  if (_impl_.created_at_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.created_at_ = p;
  }
  return _impl_.created_at_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::mutable_created_at() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_created_at();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.created_at)
  return _msg;
}
inline void Book::set_allocated_created_at(::PROTOBUF_NAMESPACE_ID::Timestamp* created_at) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_at_);
  }
  if (created_at) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(created_at));
    if (message_arena != submessage_arena) {
      created_at = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, created_at, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.created_at_ = created_at;
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.created_at)
}

// .google.protobuf.Timestamp updated_at = 21;
inline bool Book::_internal_has_updated_at() const {
  return this != internal_default_instance() && _impl_.updated_at_ != nullptr;
}
inline bool Book::has_updated_at() const {
  return _internal_has_updated_at();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::_internal_updated_at() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.updated_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Book::updated_at() const {
  // @@protoc_insertion_point(field_get:lists.book.Book.updated_at)
  return _internal_updated_at();
}
inline void Book::unsafe_arena_set_allocated_updated_at(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* updated_at) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.updated_at_);
  }
  _impl_.updated_at_ = updated_at;
  if (updated_at) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lists.book.Book.updated_at)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::release_updated_at() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.updated_at_;
  _impl_.updated_at_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::unsafe_arena_release_updated_at() {
  // @@protoc_insertion_point(field_release:lists.book.Book.updated_at)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.updated_at_;
  _impl_.updated_at_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::_internal_mutable_updated_at() {
  
  if (_impl_.updated_at_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.updated_at_ = p;
  }
  return _impl_.updated_at_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Book::mutable_updated_at() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_updated_at();
  // @@protoc_insertion_point(field_mutable:lists.book.Book.updated_at)
  return _msg;
}
inline void Book::set_allocated_updated_at(::PROTOBUF_NAMESPACE_ID::Timestamp* updated_at) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.updated_at_);
  }
  if (updated_at) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(updated_at));
    if (message_arena != submessage_arena) {
      updated_at = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, updated_at, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.updated_at_ = updated_at;
  // @@protoc_insertion_point(field_set_allocated:lists.book.Book.updated_at)
}

// -------------------------------------------------------------------

// BookCard

// int64 id = 1;
inline void BookCard::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t BookCard::_internal_id() const {
  return _impl_.id_;
}
inline int64_t BookCard::id() const {
  // @@protoc_insertion_point(field_get:lists.book.BookCard.id)
  return _internal_id();
}
inline void BookCard::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void BookCard::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:lists.book.BookCard.id)
}

// string title = 2;
inline void BookCard::clear_title() {
  _impl_.title_.ClearToEmpty();
}
inline const std::string& BookCard::title() const {
  // @@protoc_insertion_point(field_get:lists.book.BookCard.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BookCard::set_title(ArgT0&& arg0, ArgT... args) {
 
 _impl_.title_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lists.book.BookCard.title)
}
inline std::string* BookCard::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:lists.book.BookCard.title)
  return _s;
}
inline const std::string& BookCard::_internal_title() const {
  return _impl_.title_.Get();
}
inline void BookCard::_internal_set_title(const std::string& value) {
  
  _impl_.title_.Set(value, GetArenaForAllocation());
}
inline std::string* BookCard::_internal_mutable_title() {
  
  return _impl_.title_.Mutable(GetArenaForAllocation());
}
inline std::string* BookCard::release_title() {
  // @@protoc_insertion_point(field_release:lists.book.BookCard.title)
  return _impl_.title_.Release();
}
inline void BookCard::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  _impl_.title_.SetAllocated(title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lists.book.BookCard.title)
}

// string cover_image_url = 3;
inline void BookCard::clear_cover_image_url() {
  _impl_.cover_image_url_.ClearToEmpty();
}
inline const std::string& BookCard::cover_image_url() const {
  // @@protoc_insertion_point(field_get:lists.book.BookCard.cover_image_url)
  return _internal_cover_image_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BookCard::set_cover_image_url(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cover_image_url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lists.book.BookCard.cover_image_url)
}
inline std::string* BookCard::mutable_cover_image_url() {
  std::string* _s = _internal_mutable_cover_image_url();
  // @@protoc_insertion_point(field_mutable:lists.book.BookCard.cover_image_url)
  return _s;
}
inline const std::string& BookCard::_internal_cover_image_url() const {
  return _impl_.cover_image_url_.Get();
}
inline void BookCard::_internal_set_cover_image_url(const std::string& value) {
  
  _impl_.cover_image_url_.Set(value, GetArenaForAllocation());
}
inline std::string* BookCard::_internal_mutable_cover_image_url() {
  
  return _impl_.cover_image_url_.Mutable(GetArenaForAllocation());
}
inline std::string* BookCard::release_cover_image_url() {
  // @@protoc_insertion_point(field_release:lists.book.BookCard.cover_image_url)
  return _impl_.cover_image_url_.Release();
}
inline void BookCard::set_allocated_cover_image_url(std::string* cover_image_url) {
  if (cover_image_url != nullptr) {
    
  } else {
    
  }
  _impl_.cover_image_url_.SetAllocated(cover_image_url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cover_image_url_.IsDefault()) {
    _impl_.cover_image_url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lists.book.BookCard.cover_image_url)
}

// .lists.book.ReadingStatus status = 4;
inline void BookCard::clear_status() {
  _impl_.status_ = 0;
}
inline ::lists::book::ReadingStatus BookCard::_internal_status() const {
  return static_cast< ::lists::book::ReadingStatus >(_impl_.status_);
}
inline ::lists::book::ReadingStatus BookCard::status() const {
  // @@protoc_insertion_point(field_get:lists.book.BookCard.status)
  return _internal_status();
}
inline void BookCard::_internal_set_status(::lists::book::ReadingStatus value) {
  
  _impl_.status_ = value;
}
inline void BookCard::set_status(::lists::book::ReadingStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:lists.book.BookCard.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace book
}  // namespace lists

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::lists::book::ReadingStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::lists::book::ReadingStatus>() {
  return ::lists::book::ReadingStatus_descriptor();
}
template <> struct is_proto_enum< ::lists::book::Rating> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::lists::book::Rating>() {
  return ::lists::book::Rating_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_book_2eproto
